=== Elenitaferr/WsVisualStudio/13_Actividad_DTD_XSD/Empresa2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

        <xs:element name="empresa">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="NIF" type="xs:string"/>
              <xs:element name="espanola" type="xs:boolean"/>
              <xs:element name="capitalSocial" type="xs:decimal"/>
              <xs:element name="direccion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tipoVia" type="xs:string"/>
                    <xs:element name="nombreVia" type="xs:string"/>
                    <xs:element name="codigoPostal" type="xs:string"/>
                    <xs:element name="pais" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="empleados">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="empleado" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre" type="xs:string"/>
                          <xs:element name="apellidos" type="xs:string" maxOccurs="unbounded"/>
                          <xs:element name="DNI" type="xs:string"/>
                          <xs:element name="extranjero" type="xs:boolean"/>
                          <xs:element name="fechaNacimiento" type="xs:date"/>
                          <xs:element name="salario" type="xs:decimal"/>
                          <xs:element name="direccionEmpleado">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="pais" type="xs:string"/>
                                <xs:element name="tipoVia" type="xs:string"/>
                                <xs:element name="nombreVia" type="xs:string"/>
                                <xs:element name="codigoPostal" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="estaCasado" type="xs:boolean"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

</xs:schema>

=== Elenitaferr/WsVisualStudio/13_Actividad_DTD_XSD/Empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="Empresa2.xsd">
    <nombre>Elena S.L</nombre>
    <NIF>12345678A</NIF>
    <espanola>true</espanola>
    <capitalSocial>100567.124</capitalSocial>
    <direccion>
        <tipoVia>Calle</tipoVia>
        <nombreVia>Bretón de los Herreros</nombreVia>
        <codigoPostal>28003</codigoPostal>
        <pais>España</pais>
    </direccion>
    <empleados>
        <empleado>
            <nombre>Elena</nombre>
            <apellidos>Fernández</apellidos>
            <apellidos>Cañizares</apellidos>
            <DNI>05316967B</DNI>
            <extranjero>false</extranjero>
            <fechaNacimiento>1999-05-12</fechaNacimiento>
            <salario>1400.78</salario>
            <direccionEmpleado>
                <pais>España</pais>
                <tipoVia>Calle</tipoVia>
                <nombreVia>Ponzano</nombreVia>
                <codigoPostal>28003</codigoPostal>
            </direccionEmpleado>
            <estaCasado>false</estaCasado>
        </empleado>
        <empleado>
            <nombre>Juan</nombre>
            <apellidos>Pérez</apellidos>
            <apellidos>Hernandez</apellidos>
            <apellidos>López</apellidos>
            <DNI>0695485B</DNI>
            <extranjero>false</extranjero>
            <fechaNacimiento>1995-06-02</fechaNacimiento>
            <salario>1400.78</salario>
            <direccionEmpleado>
                <pais>España</pais>
                <tipoVia>Calle</tipoVia>
                <nombreVia>Santa Engracia</nombreVia>
                <codigoPostal>28003</codigoPostal>
            </direccionEmpleado>
            <estaCasado>true</estaCasado>
        </empleado>
    </empleados>
</empresa>
