=== Elenitaferr/WsVisualStudio/14_Actividad_xsd/Empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

        <xs:element name="empresa">
          <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="15"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            <xs:element name="NIF" type="xs:string"/>
            <xs:element name="capitalSocial">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="3000"/>
                    </xs:restriction>
                </xs:simpleType>
               </xs:element> 
            <xs:element name="divisaCapitalSocial">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Euros"></xs:enumeration>
                            <xs:enumeration value="Dolares"></xs:enumeration>
                            <xs:enumeration value="Yenes"></xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            <xs:element name="direccion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tipoVia">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Calle"></xs:enumeration>
                                <xs:enumeration value="Plaza"></xs:enumeration>
                                <xs:enumeration value="Via"></xs:enumeration>
                                <xs:enumeration value="Camino"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="nombreVia" type="xs:string"/>
                    <xs:element name="codigoPostal" type="xs:string"/>
                    <xs:element name="pais" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="empleados">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="empleado" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nombre" type="xs:string"/>
                                <xs:element name="apellidos" type="xs:string" maxOccurs="unbounded"/>
                                <xs:element name="DNI" type="xs:string"/>
                                <xs:element name="extranjero" type="xs:boolean"/>
                                <xs:element name="fechaNacimiento" type="xs:date"/>
                                <xs:element name="salario">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:double">
                                                <xs:minInclusive value="900"/>
                                                <xs:maxInclusive value="5000"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                </xs:element>
                                <xs:element name="direccionEmpleado">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="pais" type="xs:string"/>
                                            <xs:element name="tipoVia" type="xs:string"/>
                                            <xs:element name="nombreVia">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:maxLength value="250"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                            <xs:element name="codigoPostal" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="estaCasado" minOccurs="0">
                                    <xs:complexType />
                                </xs:element>
                            </xs:sequence>
                            <xs:attribute name="DNI" use="required">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="9"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="NIF" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="9"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="fechaCreacion" type="xs:date"/>
            <xs:attribute name="nacionalidad" type="xs:string" fixed="EspaÃ±ola"/>
          </xs:complexType>
        </xs:element>

</xs:schema>

=== Elenitaferr/WsVisualStudio/14_Actividad_xsd/Empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa NIF="256985125" nacionalidad="Española" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="Empresa.xsd">
    <nombre>Elena S.L</nombre>
    <NIF>12345678A</NIF>
    <capitalSocial>3356</capitalSocial>
    <divisaCapitalSocial>Euros</divisaCapitalSocial>
    <direccion>
        <tipoVia>Calle</tipoVia>
        <nombreVia>Bretón de los Herreros</nombreVia>
        <codigoPostal>28003</codigoPostal>
        <pais>España</pais>
    </direccion>
    <empleados>
        <empleado DNI="25698454L">
            <nombre>Elena</nombre>
            <apellidos>Fernández</apellidos>
            <apellidos>Cañizares</apellidos>
            <DNI>05316967B</DNI>
            <extranjero>false</extranjero>
            <fechaNacimiento>1999-05-12</fechaNacimiento>
            <salario>1400.78</salario>
            <direccionEmpleado>
                <pais>España</pais>
                <tipoVia>Calle</tipoVia>
                <nombreVia>Ponzano</nombreVia>
                <codigoPostal>28003</codigoPostal>
            </direccionEmpleado>
        </empleado>
        <empleado DNI="56326598K">
            <nombre>Juan</nombre>
            <apellidos>Pérez</apellidos>
            <apellidos>Hernandez</apellidos>
            <apellidos>López</apellidos>
            <DNI>0695485B</DNI>
            <extranjero>false</extranjero>
            <fechaNacimiento>1995-06-02</fechaNacimiento>
            <salario>1085.98</salario>
            <direccionEmpleado>
                <pais>España</pais>
                <tipoVia>Calle</tipoVia>
                <nombreVia>Santa Engracia</nombreVia>
                <codigoPostal>28003</codigoPostal>
            </direccionEmpleado>
            <estaCasado/>
        </empleado>
    </empleados>
</empresa>
